### ISSUE TITLE
beets.mediafile is deprecated

### ISSUE THREAD

**Issue by boredness** [adammillerio/beets-copyartifacts#3]
/home/boredness/.local/lib/python3.10/site-packages/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
beets version 1.6.0
Python version 3.10.2
plugins: copyartifacts, discogs, duplicates, lastgenre, lastimport, originquery

changing
`from beets.mediafile import TYPES`
to 
`from mediafile import TYPES`

fixed it for me

**Comment by Maurits2014** [comment]
For extra clarification: the .py file is located here:

/usr/lib/python3.9/site-packages/beetsplug/copyartifacts.py
